
DEFAULT_TITLE = "Timeline des personnages de Reflets d'Acide"
PATH_TEMPLATE = './sagas-mp3/Reflets/Textes/Reflets-{}.html'

CHAR_ALIASES = {
    'DRAGONNE': 'ALIA',
    'SACHER': 'SACHER-MASOCH',
    'BELIAL': 'BÉLIAL',
    'DEMON': 'DEMONS',
    'MORTYS': 'MORTHYS',
    'BERNIES': 'BERNIE',
    'BERNIE 2': 'BERNIE',
    'GREDIN 1': 'GREDINS',
    'GREDIN 2': 'GREDINS',
    'GREDIN 3': 'GREDINS',
    'GREDIN 4': 'GREDINS',
    'GREDIN 5': 'GREDINS',
    'CHEF GREDIN': 'GREDINS',
    'NAIN': 'SOURDINGUE',
    # Adoprixtoxis
    'GLOOMY': 'ADOPRIXTOXIS',
    'KELLOGS': 'ADOPRIXTOXIS',
    'KEVIN': 'ADOPRIXTOXIS',
    'SYPHILIS': 'ADOPRIXTOXIS',
    # Les amis de Squikky
    'CANARD': 'SQUIKKY',
    'LOUTRE': 'SQUIKKY',
    'GRENOUILLE': 'SQUIKKY',
    'GENOUILLE': 'SQUIKKY',
}
DEFAULT_RESTRICT_CHARS = {
    'ALIA',
    'BERNIE',
    'BÉLIAL',
    'DEVIN',
    'ENORIEL',
    'KYO',
    'MORTHYS',
    'MOUMOUNE',
    'REMI',
    'ROGER',
    'SACHER-MASOCH',
    'TRICHELIEU',
    'WRANDRALL',
    'ZARAKAÏ',
    'ZEHIRMANN',
}
DEFAULT_IGNORE_CHARS = {
    'ABRUTI',
    'ARMÉE',
    'CHAT BEAUTÉ',
    'CHAT',
    'DEMONS',
    'FRÈRE DE SHAMRODIA',
    'GARS 2',
    'GARS 3',
    'GARS 4',
    'GARS 5',
    'GARS',
    'GRANDADIN',
    'GREDINS',
    'GROUPE',
    'GÉGÈNE',
    'INCONNU',
    'KONKON',
    'PETITE PÉTULIA',
    'PÉTULIA',
    'PRETRE',
    'RENÉ',
    'RICO',
    'TOUS',
    'TOUTE PETITE VOIX',
    'TRUC', 'MACHIN', 'TRUC-MACHIN',
    'TYPE',
    'VOIX',
    # Special case:
    'NARRATEUR',
}
